package engine

import (
	"net/http"
	"strings"
)

// ─────────────────────────────────────────────────────────────────────────
// V9.0 ABSOLUTE APEX — Section 1.2: WAF & CDN Evasion Engine.
//
// This module fingerprints the major WAF/CDN products from response headers
// and body signals, and provides the "smart stealth routing" decision the
// orchestrator uses to skip heavy fuzzing (XSS/SQLi/SSTI) on WAF-protected
// endpoints unless the operator passed --waf-bypass.
//
// It is intentionally pure (no network I/O of its own): callers pass in an
// already-captured status/header/body triple. This keeps the classifier
// deterministic and unit-testable, and lets both the HTTP-probe phase and the
// exploit engines share one authoritative WAF verdict.
// ─────────────────────────────────────────────────────────────────────────

// WAFVendor identifies a detected WAF/CDN product.
type WAFVendor string

const (
	WAFNone       WAFVendor = ""
	WAFCloudflare WAFVendor = "Cloudflare"
	WAFAkamai     WAFVendor = "Akamai"
	WAFImperva    WAFVendor = "Imperva/Incapsula"
	WAFAWS        WAFVendor = "AWS WAF"
	WAFSucuri     WAFVendor = "Sucuri"
	WAFF5         WAFVendor = "F5 BIG-IP ASM"
	WAFFastly     WAFVendor = "Fastly"
	WAFGeneric    WAFVendor = "Generic WAF"
)

// WAFFingerprint is the verdict of classifying a single response.
type WAFFingerprint struct {
	// Detected is true when any WAF/CDN gate signal was found.
	Detected bool
	// Vendor is the best-guess product (WAFNone when not detected).
	Vendor WAFVendor
	// Challenge is true when the response is an active challenge / block page
	// (JS challenge, CAPTCHA, 403 interstitial) rather than a passthrough CDN.
	Challenge bool
	// Signals lists the concrete evidence strings that matched (for the trail).
	Signals []string
}

// wafHeaderSignal maps a (header, lower-cased value substring) pair to a vendor.
// An empty valueSubstr matches on mere header presence.
type wafHeaderSignal struct {
	header     string
	valueSub   string
	vendor     WAFVendor
	isChalenge bool
}

var wafHeaderSignals = []wafHeaderSignal{
	// Cloudflare
	{"CF-RAY", "", WAFCloudflare, false},
	{"cf-ray", "", WAFCloudflare, false},
	{"Server", "cloudflare", WAFCloudflare, false},
	{"CF-Cache-Status", "", WAFCloudflare, false},
	{"cf-mitigated", "", WAFCloudflare, true},
	// Akamai
	{"Server", "akamaighost", WAFAkamai, false},
	{"X-Akamai-Transformed", "", WAFAkamai, false},
	{"Akamai-GRN", "", WAFAkamai, false},
	{"X-Akamai-Request-ID", "", WAFAkamai, false},
	// Imperva / Incapsula
	{"X-Iinfo", "", WAFImperva, false},
	{"X-CDN", "incapsula", WAFImperva, false},
	{"Set-Cookie", "incap_ses", WAFImperva, false},
	{"Set-Cookie", "visid_incap", WAFImperva, false},
	// AWS WAF / CloudFront
	{"X-Amzn-Waf-Action", "", WAFAWS, true},
	{"X-Amz-Cf-Id", "", WAFAWS, false},
	{"Server", "awselb", WAFAWS, false},
	// Sucuri
	{"Server", "sucuri", WAFSucuri, false},
	{"X-Sucuri-ID", "", WAFSucuri, false},
	{"X-Sucuri-Cache", "", WAFSucuri, false},
	// F5 BIG-IP ASM
	{"Set-Cookie", "ts01", WAFF5, false},
	{"Server", "big-ip", WAFF5, false},
	{"X-WA-Info", "", WAFF5, false},
	// Fastly
	{"Server", "fastly", WAFFastly, false},
	{"X-Served-By", "cache-", WAFFastly, false},
	{"Fastly-Debug-Digest", "", WAFFastly, false},
}

// wafBodySignal maps a lower-cased body substring to a vendor + challenge flag.
type wafBodySignal struct {
	sub        string
	vendor     WAFVendor
	isChalenge bool
}

var wafBodySignals = []wafBodySignal{
	// Cloudflare JS challenge / managed challenge tokens.
	{"__cf_chl_rt_tk", WAFCloudflare, true},
	{"cf_chl_opt", WAFCloudflare, true},
	{"cf-chl-", WAFCloudflare, true},
	{"__cf_chl_", WAFCloudflare, true},
	{"checking your browser", WAFCloudflare, true},
	{"just a moment", WAFCloudflare, true},
	{"attention required! | cloudflare", WAFCloudflare, true},
	{"cloudflare ray id", WAFCloudflare, true},
	// Akamai
	{"akamai reference", WAFAkamai, true},
	{"access denied</title>", WAFAkamai, true},
	{"reference&#32;&#35;", WAFAkamai, true},
	// Imperva / Incapsula
	{"incapsula incident", WAFImperva, true},
	{"_incapsula_resource", WAFImperva, true},
	{"powered by incapsula", WAFImperva, true},
	{"request unsuccessful. incapsula", WAFImperva, true},
	// AWS WAF
	{"request blocked", WAFAWS, true},
	{"the request could not be satisfied", WAFAWS, true},
	{"generated by cloudfront", WAFAWS, false},
	// Sucuri
	{"sucuri website firewall", WAFSucuri, true},
	{"access denied - sucuri", WAFSucuri, true},
	// F5
	{"the requested url was rejected", WAFF5, true},
	{"support id is", WAFF5, true},
	// Generic block/challenge vocabulary.
	{"web application firewall", WAFGeneric, true},
	{"captcha-delivery.com", WAFGeneric, true},
	{"px-captcha", WAFGeneric, true},
}

// FingerprintWAF classifies a response into a WAF/CDN verdict from its status,
// headers and (already lower-cased) body sample. It scans headers first (most
// authoritative) then body signals, and finally treats a bare 403/406/429 with
// no other explanation as a generic WAF challenge.
func FingerprintWAF(status int, headers http.Header, lowerBody string) WAFFingerprint {
	fp := WAFFingerprint{}

	for _, s := range wafHeaderSignals {
		v := headers.Get(s.header)
		if v == "" {
			// Set-Cookie may repeat; join all values for substring search.
			if strings.EqualFold(s.header, "Set-Cookie") {
				v = strings.Join(headers.Values("Set-Cookie"), "; ")
			}
			if v == "" {
				continue
			}
		}
		if s.valueSub == "" || strings.Contains(strings.ToLower(v), s.valueSub) {
			fp.Detected = true
			if fp.Vendor == WAFNone {
				fp.Vendor = s.vendor
			}
			if s.isChalenge {
				fp.Challenge = true
			}
			fp.Signals = append(fp.Signals, string(s.vendor)+" header "+s.header)
		}
	}

	for _, s := range wafBodySignals {
		if strings.Contains(lowerBody, s.sub) {
			fp.Detected = true
			if fp.Vendor == WAFNone || fp.Vendor == WAFGeneric {
				fp.Vendor = s.vendor
			}
			if s.isChalenge {
				fp.Challenge = true
			}
			fp.Signals = append(fp.Signals, string(s.vendor)+` body "`+s.sub+`"`)
		}
	}

	// A 403/406/429 with no positive vendor evidence is still very likely a WAF
	// interstitial — treat it as a generic challenge so heavy fuzzing is skipped.
	if !fp.Detected && (status == 403 || status == 406 || status == 429) {
		fp.Detected = true
		fp.Vendor = WAFGeneric
		fp.Challenge = true
		fp.Signals = append(fp.Signals, "bare block status")
	}

	return fp
}

// ShouldSkipHeavyFuzzing implements the mandate's "Smart Stealth Routing"
// decision: heavy injection fuzzing (XSS/SQLi/SSTI) is skipped on a
// WAF-protected endpoint UNLESS the operator explicitly asked for --waf-bypass.
//
//   - wafProtected: the host was fingerprinted as WAF-protected.
//   - wafBypass:    the value of the --waf-bypass flag.
//
// Returns true when the caller should SKIP heavy fuzzing for this host.
func ShouldSkipHeavyFuzzing(wafProtected, wafBypass bool) bool {
	return wafProtected && !wafBypass
}

// HeavyFuzzCategories are the injection classes gated by ShouldSkipHeavyFuzzing.
// Exposed so phases/tests can iterate a single authoritative list.
var HeavyFuzzCategories = []string{"XSS", "SQLi", "SSTI", "CommandInjection", "XXE"}

// FingerprintWAFResponse is a convenience over FingerprintWAF that lower-cases
// the body for the caller.
func FingerprintWAFResponse(status int, headers http.Header, body string) WAFFingerprint {
	return FingerprintWAF(status, headers, strings.ToLower(body))
}
