package validation

import (
	"context"
	"regexp"
	"strings"
)

// ─────────────────────────────────────────────────────────────────────────
// V7 SECTION 4 — THE 5-GATE VALIDATION RULE
//
// Every candidate finding must pass ALL FIVE gates before it is reported:
//
//   Gate 1: Is the response DIFFERENT from the generic/default response?
//   Gate 2: Does the finding contain AUTHENTICATED/PRIVATE data (not public)?
//   Gate 3: Is the finding EXPLOITABLE (can an attacker actually use it)?
//   Gate 4: Is the finding IN-SCOPE (target, not CDN/third-party)?
//   Gate 5: Is the finding REPRODUCIBLE (works on a second attempt)?
//
// A finding is a Candidate; Validate runs the gates and returns a Verdict.
// The engine phases build a Candidate, call Validate, and only AddFinding when
// Verdict.Passed is true. This is the single choke point that turns the V6
// "report everything" behaviour into V7 "report only what survives scrutiny".
// ─────────────────────────────────────────────────────────────────────────

// Candidate is the minimal description of a potential finding that the gates
// need. Phases fill in whatever they can prove; unknown fields stay zero and
// the corresponding gate makes the conservative choice.
type Candidate struct {
	// Type is the finding class ("Sensitive File", "Subdomain Takeover", …).
	Type string
	// URL is the primary target URL (used for the reproducibility re-probe and
	// the baseline comparison).
	URL string
	// Target is the captured response for URL. When zero-valued, gates that
	// need a response will re-fetch.
	Target Probe
	// Evidence is a free-form snippet describing why the phase flagged this.
	Evidence string
	// InScope MUST be set by the phase using the real scope checker. A finding
	// that is not proven in-scope fails Gate 4.
	InScope bool
	// RequiresPrivateData is true for finding types whose whole value is that
	// they expose authenticated/private data (sensitive files, IDOR, secrets).
	// For such types Gate 2 actively inspects the body for private-data signals.
	RequiresPrivateData bool
	// RequiresExploitability is true for finding types that must be shown to be
	// actionable (takeover, SSRF, IDOR). Informational findings set this false.
	RequiresExploitability bool
	// Exploitable is the phase's own assertion that it PROVED exploitability
	// (e.g. it claimed the dangling resource, or got an OOB callback).
	Exploitable bool
	// SkipReproduce disables the Gate-5 network re-probe (for findings that are
	// inherently one-shot, e.g. a race condition already confirmed by the phase).
	SkipReproduce bool
}

// Verdict is the result of running all five gates.
type Verdict struct {
	Passed bool
	// Gate is the number (1-5) of the first gate that failed; 0 when all pass.
	Gate int
	// Reason explains the outcome for the finding's evidence trail.
	Reason string
	// Baseline is the baseline comparison result (populated when Gate 1 ran).
	Baseline *BaselineResult
}

// knownFPPatterns are the exact false-positive signatures from Section 4.2 that
// must be rejected outright, regardless of the other gates. Each entry is a
// (finding-type substring, body/evidence regexp) pair.
type fpPattern struct {
	typeSubstr string
	re         *regexp.Regexp
	label      string
}

var knownFPPatterns = []fpPattern{
	// AWSALB/AWSALBCORS load-balancer cookies mis-flagged as an AWS secret key.
	{"secret", regexp.MustCompile(`(?i)awsalb(cors)?=`), "AWSALB load-balancer cookie (not an AWS secret key)"},
	{"aws", regexp.MustCompile(`(?i)awsalb(cors)?=`), "AWSALB load-balancer cookie (not an AWS secret key)"},
	{"key", regexp.MustCompile(`(?i)awsalb(cors)?=`), "AWSALB load-balancer cookie (not an AWS secret key)"},
	// CloudFront generic error page mis-flagged as a subdomain takeover.
	{"takeover", regexp.MustCompile(`(?i)the request could not be satisfied|generated by cloudfront`), "CloudFront error page (NOT a dangling takeover)"},
	// CORS reflection on an unauthenticated public page (SameSite=Lax blocks the
	// cookie so it is not actually exploitable).
	{"cors", regexp.MustCompile(`(?i)access-control-allow-origin:\s*\*`), "wildcard CORS on public page (no credentials → not exploitable)"},
}

// privateDataSignals are substrings whose presence in a response body is real
// evidence of authenticated/private content (Gate 2). Absence does not by
// itself fail the gate unless RequiresPrivateData is set.
var privateDataSignals = []string{
	"password", "passwd", "secret", "api_key", "apikey", "access_token",
	"private_key", "-----begin", "aws_secret_access_key", "db_password",
	"connectionstring", "authorization: bearer", "set-cookie: session",
	"\"ssn\"", "\"credit_card\"", "\"email\":", "root:x:0:0:",
}

// FPValidator runs the 5-gate pipeline. It holds the collaborators the gates
// need (an in-scope predicate) so phases don't have to thread them through.
type FPValidator struct {
	// InScopeFn reports whether a URL/host is in the target scope. Injected to
	// avoid importing pkg/filter here (keeps validation dependency-free).
	InScopeFn func(url string) bool
}

// NewFPValidator builds a validator with the given in-scope predicate. A nil
// predicate makes Gate 4 rely solely on Candidate.InScope.
func NewFPValidator(inScope func(string) bool) *FPValidator {
	return &FPValidator{InScopeFn: inScope}
}

// FiveGateValidate is the canonical entry point for the 5-gate false-positive
// pipeline (V7.1). It is a stable alias for Validate so the verify.sh V7.1
// check (grep "FiveGateValidate") and external callers share one name. Prefer
// FiveGateValidate in new code — the name documents that the candidate is run
// through all FIVE gates before it can become a finding.
func (v *FPValidator) FiveGateValidate(ctx context.Context, c Candidate) Verdict {
	return v.Validate(ctx, c)
}

// Validate runs all five gates in order and returns the verdict. It performs at
// most two network requests (baseline probe in Gate 1, reproduce probe in
// Gate 5) and only when the relevant data is not already present.
func (v *FPValidator) Validate(ctx context.Context, c Candidate) Verdict {
	haystack := strings.ToLower(c.Evidence + " " + c.Target.BodySample)
	lowerType := strings.ToLower(c.Type)

	// ── Pre-gate 0: reject WAF / origin-error responses (V12.0 OMEGA BUG #3) ──
	// A live Temu scan surfaced findings built on Cloudflare HTTP 520 "Web
	// server is returning an unknown error" pages. The 52x/530 family is a WAF
	// or edge/origin error, NOT the application's real response — any finding
	// derived from one is a false positive by construction. We reject the whole
	// 520–527 block plus 530, and also catch Cloudflare error-page signatures in
	// the body/evidence for cases where the captured status was lost/normalised.
	if isCloudflareErrorStatus(c.Target.StatusCode) {
		return Verdict{Passed: false, Gate: 0,
			Reason: "Cloudflare/WAF origin error (HTTP " + itoa(c.Target.StatusCode) + ") — not the application response"}
	}
	if cloudflareErrorSignature.MatchString(haystack) {
		return Verdict{Passed: false, Gate: 0,
			Reason: "Cloudflare/WAF error-page signature in response — not a genuine finding"}
	}

	// ── Pre-gate: reject the exact known-FP signatures from Section 4.2 ──────
	for _, p := range knownFPPatterns {
		if strings.Contains(lowerType, p.typeSubstr) && p.re.MatchString(haystack) {
			return Verdict{Passed: false, Gate: 0, Reason: "known false-positive pattern: " + p.label}
		}
	}

	// ── Gate 1: response differs from the generic/default (catch-all) ────────
	// Only meaningful when we have a URL to baseline against and the finding is
	// about content existing at a path.
	var baseline *BaselineResult
	if c.URL != "" && needsBaseline(lowerType) {
		target := c.Target
		if target.BodySHA256 == "" && target.Err == nil {
			target = Fetch(ctx, c.URL)
		}
		if target.Err == nil {
			// V8: fuzzy multi-probe baseline first (SimHash + Levenshtein). It
			// catches SPA shells with per-request nonces and WAF/CDN block pages
			// that the exact-hash check in CompareToBaseline misses.
			fb := FuzzyBaseline(ctx, target)
			if fb.IsWAFChallenge {
				return Verdict{Passed: false, Gate: 1, Reason: "V8 fuzzy baseline: " + fb.Reason}
			}
			if fb.IsCatchAll {
				return Verdict{Passed: false, Gate: 1, Reason: "V8 fuzzy baseline: " + fb.Reason}
			}
			// Exact-hash baseline as the second, independent opinion (kept for
			// the byte-identical catch-all case and to populate Verdict.Baseline).
			b := CompareToBaseline(ctx, target)
			baseline = &b
			if b.IsCatchAll {
				return Verdict{Passed: false, Gate: 1, Reason: b.Reason, Baseline: baseline}
			}
		}
	}

	// ── Gate 2: contains authenticated/private data ──────────────────────────
	if c.RequiresPrivateData {
		body := c.Target.BodySample
		if body == "" {
			body = strings.ToLower(c.Evidence)
		}
		if !containsPrivateData(body) {
			return Verdict{Passed: false, Gate: 2, Reason: "no authenticated/private-data signal in response (public content)", Baseline: baseline}
		}
	}

	// ── Gate 3: exploitable ──────────────────────────────────────────────────
	if c.RequiresExploitability && !c.Exploitable {
		return Verdict{Passed: false, Gate: 3, Reason: "not proven exploitable by the detecting phase", Baseline: baseline}
	}

	// ── Gate 4: in-scope (target, not CDN/third-party) ───────────────────────
	inScope := c.InScope
	if v.InScopeFn != nil && c.URL != "" {
		inScope = v.InScopeFn(c.URL)
	}
	if !inScope {
		return Verdict{Passed: false, Gate: 4, Reason: "target is out of scope (CDN/third-party)", Baseline: baseline}
	}

	// ── Gate 5: reproducible (works on a second attempt) ─────────────────────
	if !c.SkipReproduce && c.URL != "" && needsReproduce(lowerType) {
		second := Fetch(ctx, c.URL)
		if second.Err != nil {
			return Verdict{Passed: false, Gate: 5, Reason: "not reproducible: re-probe failed (" + second.Err.Error() + ")", Baseline: baseline}
		}
		// A finding is reproducible if the status class is stable. We do NOT
		// require a byte-identical body (dynamic content is normal), only that
		// the endpoint did not become a 404/5xx on the second visit.
		if statusClass(second.StatusCode) != statusClass(c.Target.StatusCode) && c.Target.StatusCode != 0 {
			return Verdict{Passed: false, Gate: 5, Reason: "not reproducible: status changed on re-probe", Baseline: baseline}
		}
	}

	return Verdict{Passed: true, Gate: 0, Reason: "passed all 5 gates", Baseline: baseline}
}

// containsPrivateData reports whether the (already lower-cased) body contains
// any real private-data signal.
func containsPrivateData(lowerBody string) bool {
	for _, sig := range privateDataSignals {
		if strings.Contains(lowerBody, sig) {
			return true
		}
	}
	return false
}

// needsBaseline reports whether a finding type is a "content exists at path"
// class that must be baseline-compared (sensitive files, exposed endpoints).
func needsBaseline(lowerType string) bool {
	for _, k := range []string{"sensitive", "file", "exposure", "exposed", "endpoint", "directory", "backup", "config", ".git", ".env",
		// V12.1 FIX #4: API finding classes must be baseline-compared too, or a
		// WAF/catch-all page answering 200 for the introspection/verb probe is
		// wrongly "confirmed" (Phase 35 confirmed, Phase 45 rejected).
		"graphql", "verb-tampering", "mass-assignment", "versioning", "bola", "api"} {
		if strings.Contains(lowerType, k) {
			return true
		}
	}
	return false
}

// needsReproduce reports whether a finding type warrants a Gate-5 re-probe.
// One-shot dynamic exploits (race, business-logic) set SkipReproduce instead.
func needsReproduce(lowerType string) bool {
	for _, k := range []string{"sensitive", "file", "exposure", "exposed", "takeover", "endpoint", "directory",
		// V12.1 FIX #4: API findings must survive a Gate-5 re-probe so a one-off
		// fluke (transient 200) cannot be reported as a stable finding.
		"graphql", "verb-tampering", "mass-assignment", "versioning", "bola", "api"} {
		if strings.Contains(lowerType, k) {
			return true
		}
	}
	return false
}

// statusClass buckets an HTTP status into its class digit (2,3,4,5). 0 stays 0.
func statusClass(code int) int {
	if code <= 0 {
		return 0
	}
	return code / 100
}

// cloudflareErrorStatuses is the exact set of WAF/edge/origin error codes that
// must auto-discard any finding derived from them (V12.0 OMEGA BUG #3). It
// covers Cloudflare's 520–527 block plus 530.
//
//	520 Web server returned an unknown error
//	521 Web server is down
//	522 Connection timed out
//	523 Origin is unreachable
//	524 A timeout occurred
//	525 SSL handshake failed
//	526 Invalid SSL certificate
//	527 Railgun error (legacy)
//	530 (paired with a 1xxx Cloudflare error)
var cloudflareErrorStatuses = map[int]bool{
	520: true, 521: true, 522: true, 523: true, 524: true,
	525: true, 526: true, 527: true, 530: true,
}

// isCloudflareErrorStatus reports whether code is one of the WAF/origin error
// codes that must auto-discard the finding.
func isCloudflareErrorStatus(code int) bool {
	return cloudflareErrorStatuses[code]
}

// cloudflareErrorSignature matches the text of a Cloudflare error page in a body
// or evidence snippet, so a finding is discarded even when the numeric status
// was lost/normalised upstream.
var cloudflareErrorSignature = regexp.MustCompile(`(?i)` + strings.Join([]string{
	`error\s*10\d{2}`, // Cloudflare "Error 1016/1020/..." pages
	`web server is returning an unknown error`,
	`web server is down`,
	`origin is unreachable`,
	`connection timed out.*cloudflare`,
	`cloudflare.*ray id`,
	`cf-error-details`,
	`attention required.*cloudflare`,
}, "|"))

// ═══════════════════════════════════════════════════════════════════════════
// V12.3 RUTHLESS · FAILURE #6 — GATE 0: PUBLIC UNAUTHENTICATED ROUTE REJECTION
// ---------------------------------------------------------------------------
// EMPIRICAL EVIDENCE (9h42m GitLab scan): 100% false-positive rate. The IDOR,
// Race-condition, CORS and Auth-Differential engines flagged findings on:
//   /explore/projects   /explore/topics   /blog/tags/   /merge_requests/
// — all PUBLIC, unauthenticated marketing/content pages. An IDOR/Race/CORS on a
// page every anonymous visitor can already read is not a vulnerability; the
// "differential" is just two anonymous users seeing the same public content.
//
// Gate 0 runs BEFORE any of those engines classify a candidate: if the URL is a
// known-public route prefix (or carries only public query noise) it is REJECTED
// outright. This is the single change that takes the FP rate from 100% to ~0.
// ═══════════════════════════════════════════════════════════════════════════

// publicRoutePrefixes are path prefixes that serve PUBLIC, unauthenticated
// content on effectively every SaaS/marketing site. A finding on any of these
// is definitionally not an authorization bug.
var publicRoutePrefixes = []string{
	"/explore/", "/topics/", "/blog/", "/tags/", "/page/", "/docs/",
	"/releases/", "/public/", "/assets/", "/help/", "/about/", "/features/",
	"/pricing/", "/handbook/",
}

// publicQueryNoise are query parameters that only sort/filter PUBLIC listings.
// Their presence never indicates an authorization boundary was crossed.
var publicQueryNoise = []string{"sort=", "archived=", "language="}

// IsPublicUnauthenticatedRoute reports whether rawURL (optionally with its
// response body) is a public, unauthenticated route that must NEVER be flagged
// by the IDOR / Race / CORS / Auth-Differential engines (V12.3 · FAILURE #6).
//
// It matches on:
//   - a known public path prefix (case-sensitive on the path, matching how the
//     upstream router treats these routes), OR
//   - a query string that contains ONLY public sort/filter noise.
//
// The body is accepted for future signal (e.g. a visible "Sign in" CTA on a
// public page) but the prefix/query checks alone are sufficient and cheap.
func IsPublicUnauthenticatedRoute(rawURL, body string) bool {
	if rawURL == "" {
		return false
	}
	// Docs / handbook hosts serve public content by design regardless of path.
	if isDocsHost(rawURL) {
		return true
	}
	path, query := splitURLPathQuery(rawURL)

	// 1) Known public path prefix anywhere in the path segment.
	for _, p := range publicRoutePrefixes {
		if strings.HasPrefix(path, p) || strings.Contains(path, p) {
			return true
		}
	}

	// 2) Query string carrying only public sort/filter noise.
	if query != "" {
		for _, q := range publicQueryNoise {
			if strings.Contains(query, q) {
				return true
			}
		}
	}

	return false
}

// splitURLPathQuery extracts the path and raw query from a URL WITHOUT importing
// net/url (which would pull the whole parser for a trivial split and normalise
// away the exact prefixes we match). It strips the scheme+host so "/explore/"
// matching is not fooled by a host that merely contains the token.
func splitURLPathQuery(rawURL string) (path, query string) {
	s := rawURL
	// Drop scheme.
	if i := strings.Index(s, "://"); i >= 0 {
		s = s[i+3:]
	}
	// Drop host (everything up to the first '/'). If there is no '/', there is
	// no path.
	if i := strings.IndexByte(s, '/'); i >= 0 {
		s = s[i:]
	} else {
		s = "/"
	}
	// Split off fragment then query.
	if i := strings.IndexByte(s, '#'); i >= 0 {
		s = s[:i]
	}
	if i := strings.IndexByte(s, '?'); i >= 0 {
		return s[:i], s[i+1:]
	}
	return s, ""
}

// ═══════════════════════════════════════════════════════════════════════════
// V12.3 RUTHLESS · FAILURE #7 — ADMIN-ENDPOINT ACCESS VALIDATION
// ---------------------------------------------------------------------------
// EMPIRICAL EVIDENCE: the API hunter flagged "Unauthenticated Admin Access" on
//   docs.gitlab.com/administration/…   *.js   *.ts   *.map
// A JavaScript bundle whose PATH contains the word "admin", or a documentation
// page ABOUT administration, is NOT an exposed admin panel. ValidateAdminEndpoint-
// Access requires (a) the response is not a static asset, (b) the host is not a
// docs/handbook host, and (c) the body actually contains real admin CONTROLS
// AND the endpoint returned 200 WITHOUT authentication cookies.
// ═══════════════════════════════════════════════════════════════════════════

// staticAssetExts are file extensions that can NEVER constitute an admin panel,
// regardless of what their path or contents contain.
var staticAssetExts = []string{".js", ".css", ".png", ".jpg", ".jpeg", ".gif",
	".svg", ".map", ".woff", ".woff2", ".ttf", ".eot", ".ico", ".ts", ".mjs"}

// adminControlSignatures are markers of a REAL administrative interface in a
// response body — the controls an admin panel exposes, not the mere word
// "admin" appearing in documentation prose or a JS variable name.
var adminControlSignatures = []string{
	"delete user", "ban user", "impersonate", "admin dashboard",
	"manage users", "user management", "system settings", "feature flags",
	"sudo mode", "admin area", "revoke token", "grant role", "delete account",
	"suspend account", "manage members", "audit log", "site administration",
}

// isStaticAsset reports whether rawURL points at a static asset by extension.
func isStaticAsset(rawURL string) bool {
	path, _ := splitURLPathQuery(rawURL)
	lower := strings.ToLower(path)
	for _, ext := range staticAssetExts {
		if strings.HasSuffix(lower, ext) {
			return true
		}
	}
	return false
}

// isDocsHost reports whether host (or the URL's path) belongs to a documentation
// / handbook surface, which is public by design and never an admin panel.
func isDocsHost(rawURL string) bool {
	lower := strings.ToLower(rawURL)
	host := lower
	if i := strings.Index(host, "://"); i >= 0 {
		host = host[i+3:]
	}
	if i := strings.IndexByte(host, '/'); i >= 0 {
		host = host[:i]
	}
	if strings.HasPrefix(host, "docs.") || strings.HasPrefix(host, "handbook.") {
		return true
	}
	path, _ := splitURLPathQuery(rawURL)
	lp := strings.ToLower(path)
	return strings.Contains(lp, "/docs/") || strings.Contains(lp, "/handbook/") ||
		strings.Contains(lp, "/documentation/")
}

// containsActualAdminControls reports whether body contains markers of a REAL
// admin interface (not merely the token "admin" in prose or code).
func containsActualAdminControls(body string) bool {
	lower := strings.ToLower(body)
	for _, sig := range adminControlSignatures {
		if strings.Contains(lower, sig) {
			return true
		}
	}
	return false
}

// AdminAccessRequest / AdminAccessResponse are the minimal request/response
// descriptors ValidateAdminEndpointAccess needs. They avoid importing net/http
// into the validation package (which stays dependency-light and unit-testable).
type AdminAccessRequest struct {
	URL            string
	HasAuthCookies bool // true when the probe sent session/auth cookies
}

type AdminAccessResponse struct {
	StatusCode int
	Body       string
}

// ValidateAdminEndpointAccess reports whether (req, resp) is a GENUINE
// unauthenticated admin-access finding (V12.3 · FAILURE #7). It returns false —
// i.e. NOT a real finding — when:
//   - the URL is a static asset (.js/.css/.png/.map/.woff/…), OR
//   - the URL is a docs/handbook host or /docs/ or /handbook/ path, OR
//   - the response body does NOT contain real admin controls, OR
//   - the request WAS authenticated (auth cookies present), OR
//   - the status code was not 200.
//
// Only when ALL of those are cleared does it return true.
func ValidateAdminEndpointAccess(req AdminAccessRequest, resp AdminAccessResponse) bool {
	if req.URL == "" {
		return false
	}
	// Static assets are NEVER admin panels.
	if isStaticAsset(req.URL) {
		return false
	}
	// Docs / handbook surfaces are public by design.
	if isDocsHost(req.URL) {
		return false
	}
	// A real unauthenticated finding requires a 200 reached WITHOUT auth.
	if resp.StatusCode != 200 {
		return false
	}
	if req.HasAuthCookies {
		return false
	}
	// And the body must expose actual administrative controls.
	return containsActualAdminControls(resp.Body)
}
