package validation

import (
	"context"
	"testing"
)

// alwaysInScope is the scope oracle used by most tests.
func alwaysInScope(string) bool { return true }

// ─────────────────────────────────────────────────────────────────────────────
// Known-FP pre-gate: the exact V6 false positives must be rejected.
// ─────────────────────────────────────────────────────────────────────────────

func TestKnownFP_AWSALBCookieRejected(t *testing.T) {
	v := NewFPValidator(alwaysInScope)
	c := Candidate{
		Type:     "AWS Secret Key",
		URL:      "https://target.com/",
		InScope:  true,
		Evidence: "found Set-Cookie: AWSALB=abcdef0123456789; path=/",
	}
	verdict := v.Validate(context.Background(), c)
	if verdict.Passed {
		t.Fatalf("AWSALB cookie must be rejected as a known FP, got passed")
	}
}

func TestKnownFP_CloudFrontTakeoverRejected(t *testing.T) {
	v := NewFPValidator(alwaysInScope)
	c := Candidate{
		Type:        "Subdomain Takeover",
		URL:         "https://sub.target.com/",
		InScope:     true,
		Exploitable: true,
		Evidence:    "ERROR: The request could not be satisfied. Generated by cloudfront (CloudFront)",
	}
	verdict := v.Validate(context.Background(), c)
	if verdict.Passed {
		t.Fatalf("CloudFront error page must not be flagged as takeover")
	}
}

func TestKnownFP_WildcardCORSPublicRejected(t *testing.T) {
	v := NewFPValidator(alwaysInScope)
	c := Candidate{
		Type:     "CORS Misconfiguration",
		URL:      "https://target.com/public",
		InScope:  true,
		Evidence: "response header Access-Control-Allow-Origin: * on a public page",
	}
	verdict := v.Validate(context.Background(), c)
	if verdict.Passed {
		t.Fatalf("wildcard CORS on public page must be rejected")
	}
}

// ─────────────────────────────────────────────────────────────────────────────
// Gate 3 (exploitability) and Gate 4 (scope).
// ─────────────────────────────────────────────────────────────────────────────

func TestGate3_NotExploitableRejected(t *testing.T) {
	v := NewFPValidator(alwaysInScope)
	c := Candidate{
		Type:                   "idor",
		URL:                    "https://target.com/a?id=1",
		InScope:                true,
		RequiresExploitability: true,
		Exploitable:            false, // phase could not prove it
		SkipReproduce:          true,
	}
	verdict := v.Validate(context.Background(), c)
	if verdict.Passed || verdict.Gate != 3 {
		t.Fatalf("expected Gate-3 rejection for unproven exploit, got %+v", verdict)
	}
}

func TestGate4_OutOfScopeRejected(t *testing.T) {
	v := NewFPValidator(func(string) bool { return false }) // everything out of scope
	c := Candidate{
		Type:          "session-hardening",
		URL:           "https://cdn.thirdparty.net/x",
		Evidence:      "missing HttpOnly",
		SkipReproduce: true,
	}
	verdict := v.Validate(context.Background(), c)
	if verdict.Passed || verdict.Gate != 4 {
		t.Fatalf("expected Gate-4 out-of-scope rejection, got %+v", verdict)
	}
}

// ─────────────────────────────────────────────────────────────────────────────
// A clean, exploitable, in-scope, one-shot finding passes all gates.
// ─────────────────────────────────────────────────────────────────────────────

func TestValidCandidatePasses(t *testing.T) {
	v := NewFPValidator(alwaysInScope)
	c := Candidate{
		Type:                   "ssti",
		URL:                    "https://target.com/p?q=x",
		InScope:                true,
		RequiresExploitability: true,
		Exploitable:            true,
		SkipReproduce:          true, // exploit already confirmed by the phase
		Evidence:               "param q evaluated {{1337*1339}} → 1790243 appeared",
	}
	verdict := v.Validate(context.Background(), c)
	if !verdict.Passed {
		t.Fatalf("clean exploitable in-scope candidate should pass, got %+v", verdict)
	}
}

// ─────────────────────────────────────────────────────────────────────────────
// Gate 2 (private data): a "sensitive file" finding with no private-data
// signal in the evidence must be rejected as public content.
// ─────────────────────────────────────────────────────────────────────────────

func TestGate2_NoPrivateDataRejected(t *testing.T) {
	v := NewFPValidator(alwaysInScope)
	c := Candidate{
		Type:                "Config Exposure",
		URL:                 "https://target.com/robots.txt",
		InScope:             true,
		RequiresPrivateData: true,
		SkipReproduce:       true,
		Evidence:            "User-agent: * Disallow: /admin", // public, no secret
	}
	// needsBaseline is true for "exposure" types; with no reachable server the
	// baseline fetch errors and is skipped, so Gate 2 is the decisive gate.
	verdict := v.Validate(context.Background(), c)
	if verdict.Passed {
		t.Fatalf("public content must fail Gate 2 (no private data), got passed")
	}
}

func TestGate2_PrivateDataPasses(t *testing.T) {
	v := NewFPValidator(alwaysInScope)
	c := Candidate{
		Type:                "Secret Leak",
		URL:                 "https://target.com/x",
		InScope:             true,
		RequiresPrivateData: true,
		SkipReproduce:       true,
		Evidence:            `leaked aws_secret_access_key=AKIA... and db_password=hunter2`,
	}
	verdict := v.Validate(context.Background(), c)
	if !verdict.Passed {
		t.Fatalf("evidence containing real private-data signals should pass, got %+v", verdict)
	}
}

// ─────────────────────────────────────────────────────────────────────────────
// randomToken must produce distinct tokens (baseline probe relies on this).
// ─────────────────────────────────────────────────────────────────────────────

func TestRandomTokenDistinct(t *testing.T) {
	a := randomToken(20)
	b := randomToken(20)
	if a == "" || len(a) != 20 {
		t.Fatalf("randomToken length wrong: %q", a)
	}
	if a == b {
		t.Fatalf("randomToken should not repeat: %q == %q", a, b)
	}
}
